version: "3.9"

services:
  server: 
    build: 
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - './cache:/root/.ollama'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]